import type { Runbook } from '../../types';

export const INITIAL_RUNBOOKS: Runbook[] = [
  {
    id: 'rb-001',
    title: 'Airflow DAG Deadlock Remediation',
    category: 'Airflow',
    description: 'Autonomous remediation steps for clearing stuck database locks and scheduler heartbeats in Apache Airflow clusters under high concurrency.',
    source: 'Markdown',
    status: 'ACTIVE',
    last_updated: '2026-05-12T10:15:00Z',
    last_updated_by: 'AgenticGuard (AI)',
    risk_level: 'Medium',
    ai_usage_enabled: true,
    rag_enabled: true,
    ai_approved: true,
    human_verified: true,
    steps: [
      'Query pg_stat_activity to detect long-running transactions holding exclusive locks on task_instance table.',
      'Terminate blocking PIDs gracefully using pg_terminate_backend if idle in transaction exceeds SLA.',
      'Restart isolated Celery workers displaying stale heartbeat timestamps.',
      'Trigger downstream dependent DAG recovery sequence via Airflow REST API.'
    ],
    associated_systems: ['Production Postgres Cluster', 'Airflow Scheduler Pods', 'Celery Workers'],
    last_incidents_used: ['INC-8492', 'INC-8301'],
    version_history: ['v1.2.0 (Auto-optimized)', 'v1.1.0', 'v1.0.0'],
    tags: ['deadlock', 'scheduler', 'postgres', 'high-concurrency'],
    ai_confidence_score: 98,
    linked_incidents_count: 14
  },
  {
    id: 'rb-002',
    title: 'Spark OOM (Out of Memory) Triage Guide',
    category: 'Spark',
    description: 'SOP for dynamic executor memory tuning and garbage collection profiling during massive join/shuffle stage out-of-memory crashes.',
    source: 'PDF',
    status: 'ACTIVE',
    last_updated: '2026-05-11T14:22:00Z',
    last_updated_by: 'Sarah Jenkins (DataOps)',
    risk_level: 'High',
    ai_usage_enabled: true,
    rag_enabled: true,
    ai_approved: true,
    human_verified: true,
    steps: [
      'Inspect Spark Event Logs to identify skewed partitions exceeding spark.sql.shuffle.partitions allocation.',
      'Inject adaptive query execution (AQE) flags dynamically: spark.sql.adaptive.enabled=true.',
      'Increase spark.executor.memoryOverhead ratio to 0.25 for resource-intensive native library execution.',
      'Purge unneeded cached broadcast variables from JVM heap memory.'
    ],
    associated_systems: ['Databricks Runtime 14.2', 'AWS EMR Spark Clusters'],
    last_incidents_used: ['INC-8411'],
    version_history: ['v2.0.1', 'v2.0.0', 'v1.4.2'],
    tags: ['oom', 'executor', 'shuffle-skew', 'aqe'],
    ai_confidence_score: 95,
    linked_incidents_count: 8
  },
  {
    id: 'rb-003',
    title: 'Kubernetes Persistent Volume Eviction Recovery',
    category: 'Kubernetes',
    description: 'Automated script sequence for releasing orphaned VolumeAttachments and safely remounting network-attached EBS/Disk volumes to newly rescheduled StatefulSet pods.',
    source: 'TXT',
    status: 'AI GENERATED',
    last_updated: '2026-05-10T08:05:00Z',
    last_updated_by: 'AgentMesh Orchestrator',
    risk_level: 'High',
    ai_usage_enabled: true,
    rag_enabled: true,
    ai_approved: true,
    human_verified: false,
    steps: [
      'Force delete stuck Terminating pods with zero grace period if node status is NotReady.',
      'Patch VolumeAttachment objects to remove finalizers preventing cloud storage detachment.',
      'Verify CSI driver health endpoints on active target nodes.',
      'Monitor volume mount completion events in targeted namespace.'
    ],
    associated_systems: ['EKS Core Clusters', 'AWS EBS CSI Driver'],
    last_incidents_used: ['INC-8109', 'INC-7902', 'INC-7881'],
    version_history: ['v1.0.0 (AI Draft)'],
    tags: ['storage', 'csi', 'ebs', 'statefulset'],
    ai_confidence_score: 91,
    linked_incidents_count: 5
  },
  {
    id: 'rb-004',
    title: 'Kafka Consumer Lag Spike Mitigator',
    category: 'Infrastructure',
    description: 'Procedures to dynamically scale partition consumers and tune max.poll.records to prevent partition rebalances during massive upstream data backfill events.',
    source: 'DOCX',
    status: 'DRAFT',
    last_updated: '2026-05-08T16:40:00Z',
    last_updated_by: 'Alex Rivera (SRE)',
    risk_level: 'Low',
    ai_usage_enabled: false,
    rag_enabled: false,
    ai_approved: false,
    human_verified: true,
    steps: [
      'Check consumer group offset metrics via Burrow/Prometheus dashboards.',
      'Temporarily scale consumer pod replica count proportionally to partition load.',
      'Tune max.poll.interval.ms to accommodate CPU-intensive downstream record parsing.'
    ],
    associated_systems: ['Confluent Cloud Clusters', 'Microservice Ingestion Layer'],
    last_incidents_used: [],
    version_history: ['v0.1.0-draft'],
    tags: ['kafka', 'consumer-lag', 'streaming', 'rebalance'],
    ai_confidence_score: 78,
    linked_incidents_count: 0
  },
  {
    id: 'rb-005',
    title: 'PostgreSQL Read-Replica Lag Synchronization',
    category: 'Database',
    description: 'SOP to diagnose streaming replication delays, inspect wal_receiver status, and clear massive vacuuming blockages on downstream analytics instances.',
    source: 'Markdown',
    status: 'ACTIVE',
    last_updated: '2026-05-05T11:12:00Z',
    last_updated_by: 'AgenticGuard (AI)',
    risk_level: 'Medium',
    ai_usage_enabled: true,
    rag_enabled: true,
    ai_approved: true,
    human_verified: true,
    steps: [
      'Measure replication lag byte distance using pg_stat_replication on master instance.',
      'Verify if hot_standby_feedback is causing excessive dead tuple retention.',
      'Temporarily pause aggressive reporting cronjobs querying replica instances.',
      'Issue immediate checkpoint command if WAL segment shipping stalls.'
    ],
    associated_systems: ['Aurora Global Database', 'Analytics Read Replicas'],
    last_incidents_used: ['INC-7654'],
    version_history: ['v1.3.1', 'v1.3.0'],
    tags: ['replication', 'wal', 'postgres', 'lag'],
    ai_confidence_score: 96,
    linked_incidents_count: 11
  }
];
